version: "2.0"
services:
  lidar-edge:
    image: lidar-edge
    container_name: lidar-edge
    network_mode: "host"
    restart: always
    volumes:
      - type: bind
        source: /home/infolab/Desktop/lab_lidar_system/lidar_edge
        target: /ws/ws_livox/src/lidar_subscriber/scripts
      - type: bind
        source: /home/infolab/Desktop/lab_lidar_system/lidar_setting/lidar_launch
        target: /ws/ws_livox/src/livox_ros_driver/launch/
      - type: bind
        source: /home/infolab/Desktop/lab_lidar_system/lidar_setting/lidar_config
        target: /ws/ws_livox/src/livox_ros_driver/config
      - type: bind
        source: /home/infolab/Desktop/lab_lidar_system/lidar_setting/lidar_data
        target: /ws/lidar_data
      - type: bind
        source: /home/infolab/Desktop/lab_lidar_system/lidar_tuning
        target: /ws/lidar_tuning
    command: 
      - /bin/bash
      - -c
      - 'source /opt/ros/noetic/setup.bash && source /ws/ws_livox/devel/setup.bash && sudo chmod +x /ws/ws_livox/src/lidar_subscriber/scripts/lidar_sub.py && roslaunch livox_ros_driver livox_lidar.launch --screen'

    runtime: nvidia

  lidar-server:
    image: lidar-server
    container_name: lidar-server
    network_mode: "host"
    restart: always
    volumes:
      - type: bind
        source: /home/infolab/Desktop/lab_lidar_system/lidar_server
        target: /ws/lidar_server
      - type: bind
        source: /home/infolab/Desktop/lab_lidar_system/lidar_setting/lidar_data
        target: /ws/lidar_data
    command: 
      - /bin/bash
      - -c
      - 'cd /ws/lidar_server/web_app && uvicorn web_server:app --host 192.168.50.32 --port 8000 --reload & cd /ws/lidar_server && python lidar_server.py'

    runtime: nvidia